version: 2
jobs:
  build:
    docker:
      - image: growthteam/daq-ci-ubuntu

    steps:
      - checkout
      - run:
          name: "Run cmake"
          command: "cmake -H. -Bbuild"
      - run:
          name: "Run build"
          command: "cmake --build build"
