version: 2
jobs:
  build:
    docker:
      - image: growthteam/daq-ci-ubuntu

    steps:
      - checkout
      - run:
          name: "PWD"
          command: "pwd"
      - run:
          name: "List files"
          command: "ls"
      - run:
          name: "Run build"
          command: "mkdir build && cd build && cmake ../daq && make"
