FROM ubuntu:18.04

RUN apt update
RUN apt install -y \
  build-essential nano curl \
  binutils \
  cmake \
  dpkg-dev \
  git \
  i2c-tools \
  imagemagick \
  libboost-all-dev \
  libbz2-dev \
  libcfitsio-dev \
  libcurl4-openssl-dev \
  libexpat-dev \
  libjpeg8-dev \
  libncurses-dev \
  libssl-dev \
  libtool-bin \
  libx11-dev \
  libxerces-c-dev \
  libxext-dev \
  libxft-dev \
  libxpm-dev \
  libyaml-cpp-dev \
  libzmq3-dev \
  python-dev \
  python-smbus \
  python-zmq \
  ruby \
  ruby-dev \
  ruby-ffi \
  swig \
  texinfo \
  wget \
  wicd-curses \
  zlib1g-dev
