DetectorID: growth-fy2016s
PreTriggerSamples: 20
PostTriggerSamples: 1000
SamplesInEventPacket: 1
DownSamplingFactorForSavedWaveform: 1
ChannelEnable: [yes,yes,yes,yes]
TriggerThresholds: [2101,2096,2098,2100]
TriggerCloseThresholds: [2067, 2065, 2060, 2065]
