DetectorID: growth-fy2017a
PreTriggerSamples: 20
PostTriggerSamples: 500
SamplesInEventPacket: 1
DownSamplingFactorForSavedWaveform: 1
ChannelEnable: [yes,no,no,no]
TriggerThresholds: [2120, 2100, 2100, 2100]
TriggerCloseThresholds: [2060, 2090, 2090, 2090]
