DetectorID: growth-fy2016e
PreTriggerSamples: 20
PostTriggerSamples: 1000
SamplesInEventPacket: 1
DownSamplingFactorForSavedWaveform: 1
ChannelEnable: [yes,no,no,no]
TriggerThresholds: [2080, 4095, 4095, 4095]
TriggerCloseThresholds: [2060, 2090, 2090, 2090]
