DetectorID: growth-fy2016e
PreTriggerSamples: 20
PostTriggerSamples: 1000
SamplesInEventPacket: 1
DownSamplingFactorForSavedWaveform: 1
<<<<<<< HEAD
ChannelEnable: [yes,yes,yes,yes]
TriggerThresholds: [2080, 2100, 2100, 2100]
=======
ChannelEnable: [yes,no,no,no]
TriggerThresholds: [2080, 4095, 4095, 4095]
>>>>>>> e05a20ace979e1fcaaea3fd7851560b4e6f0d349
TriggerCloseThresholds: [2060, 2090, 2090, 2090]
