DetectorID: growth-fy2017b
PreTriggerSamples: 20
PostTriggerSamples: 500
SamplesInEventPacket: 1
DownSamplingFactorForSavedWaveform: 1
ChannelEnable: [yes,yes,yes,yes]
TriggerThresholds: [2060, 2070, 2060, 2065]
TriggerCloseThresholds: [2055, 2060, 2055, 2060]
