DetectorID: growth-fy2017
PreTriggerSamples: 20
PostTriggerSamples: 500
SamplesInEventPacket: 1
DownSamplingFactorForSavedWaveform: 1
ChannelEnable: [yes,yes,no,yes]
TriggerModes: [4, 4, 4, 4]
TriggerThresholds: [30, 30, 30, 30]
TriggerCloseThresholds: [2050, 2050, 2050, 2050]

