-- Module dcm
-- Generated by Xilinx Architecture Wizard
-- VHDL
-- Written for synthesis tool: XST

library IEEE;
use IEEE.std_logic_1164.all;
use IEEE.numeric_std.all;
Library UNISIM;
use UNISIM.Vcomponents.all;

entity clkdcm is
    port (
        RST_IN : in std_logic;
        CLKIN_IN : in std_logic;
        LOCKED_OUT : out std_logic;
        CLK2X_OUT : out std_logic;
        CLKFX_OUT : out std_logic;
        CLKFX180_OUT : out std_logic;
        CLKDV_OUT : out std_logic;
        CLKIN_IBUFG_OUT : out std_logic;
        CLK0_OUT : out std_logic);
end clkdcm;

architecture STRUCT of clkdcm is
   signal CLKIN_IBUFG : std_logic;
   signal CLKFB_IN : std_logic;
   signal CLK0_BUF : std_logic;
	signal CLKDV_BUF : std_logic;
   signal CLK2X_BUF : std_logic;
   signal CLKFX_BUF : std_logic;
   signal CLKFX180_BUF : std_logic;
   signal GND : std_logic;


begin

  DCM_SP_inst : DCM_SP
   generic map (
      CLKDV_DIVIDE => 2.0,                   -- CLKDV divide value
                                             -- (1.5,2,2.5,3,3.5,4,4.5,5,5.5,6,6.5,7,7.5,8,9,10,11,12,13,14,15,16).
      CLKFX_DIVIDE => 1,                     -- Divide value - D - (1-32)
      CLKFX_MULTIPLY => 4,                   -- Multiply value - M - (2-32)
      CLKIN_DIVIDE_BY_2 => FALSE,            -- CLKIN divide by two (TRUE/FALSE)
      CLKIN_PERIOD => 20.0,                -- Input clock period specified in nS
      CLKOUT_PHASE_SHIFT => "NONE",          -- Output phase shift (NONE, FIXED, VARIABLE)
      CLK_FEEDBACK => "1X",                  -- Feedback source (NONE, 1X, 2X)
      DESKEW_ADJUST => "SYSTEM_SYNCHRONOUS", -- SYSTEM_SYNCHRNOUS or SOURCE_SYNCHRONOUS
      DFS_FREQUENCY_MODE => "LOW",           -- Unsupported - Do not change value
      DLL_FREQUENCY_MODE => "LOW",           -- Unsupported - Do not change value
      DSS_MODE => "NONE",                    -- Unsupported - Do not change value
      DUTY_CYCLE_CORRECTION => TRUE,         -- Unsupported - Do not change value
      FACTORY_JF => X"c080",                 -- Unsupported - Do not change value
      PHASE_SHIFT => 0,                      -- Amount of fixed phase shift (-255 to 255)
      STARTUP_WAIT => FALSE                  -- Delay config DONE until DCM LOCKED (TRUE/FALSE)
   )
   port map (
      CLK0 => CLK0_BUF,         -- 1-bit 0 degree clock output
      CLK180 => open,     -- 1-bit 180 degree clock output
      CLK270 => open,     -- 1-bit 270 degree clock output
      CLK2X => CLK2X_BUF,       -- 1-bit 2X clock frequency clock output
      CLK2X180 => open, -- 1-bit 2X clock frequency, 180 degree clock output
      CLK90 => open,       -- 1-bit 90 degree clock output
      CLKDV => CLKDV_BUF,       -- 1-bit Divided clock output
      CLKFX => CLKFX_BUF,       -- 1-bit Digital Frequency Synthesizer output (DFS)
      CLKFX180 => CLKFX180_BUF, -- 1-bit 180 degree CLKFX output
      LOCKED => LOCKED_OUT,     -- 1-bit DCM Lock Output
      PSDONE => open,     -- 1-bit Phase shift done output
      STATUS => open,     -- 8-bit DCM status output
      CLKFB => CLKFB_IN,       -- 1-bit Clock feedback input
      CLKIN => CLKIN_IBUFG,       -- 1-bit Clock input
      DSSEN => open,       -- 1-bit Unsupported
      PSCLK => '0',       -- 1-bit Phase shift clock input
      PSEN => '0',         -- 1-bit Phase shift enable
      PSINCDEC => '0', -- 1-bit Phase shift increment/decrement input
      RST => RST_IN            -- 1-bit Active high reset input
   );

--   CLKIN_IBUFG_INST : IBUFG
--     port map (
--      I => CLKIN_IN,
--      O => CLKIN_IBUFG);

	CLKIN_IBUFG <= CLKIN_IN;

   CLK0_BUFG_INST : BUFG
     port map (
      I => CLK0_BUF,
      O => CLKFB_IN);

   CLKFX_BUFG_INST : BUFG
     port map (
      I => CLKFX_BUF,
      O => CLKFX_OUT);

   CLKFX180_BUFG_INST : BUFG
     port map (
      I => CLKFX180_BUF,
      O => CLKFX180_OUT);

   CLK2X_BUFG_INST : BUFG
     port map (
      I => CLK2X_BUF,
      O => CLK2X_OUT);

   CLKDV_BUFG_INST : BUFG
     port map (
      I => CLKDV_BUF,
      O => CLKDV_OUT);

   CLKIN_IBUFG_OUT <= CLKIN_IBUFG;
   CLK0_OUT <= CLKFB_IN;
   GND <= '0';
end STRUCT;

