detectorID: Belisama
hv:
    conversion:
        0: (x/3300)*105.5
        1: (x/3300)*105.5
    default:
        0: on
        1: off
control:
    constTemp:
        0: 0.054
        1: 0.0
    constCrys:
        0: 0.0
        1: 0.0
    voltBreak:
        0: 54.07
        1: 24.1
    deltaVolt:
        0: 3.0
        1: 3.0
limits:
    temperature:
        lower: -50
        upper: 55
    hv:
        0: 60
        1: 0
